---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
books <- read.csv("books.csv") # load in the data and assign to "books"

glimpse(books) #11,123 rows and 13 columns

names(books) # get a feel for the data, note - not sure why it's not showing the first 3 names of rowid, bookid and title - closing and opening RSTudio solved this issue?

head(books)

tail(books)

# check dataset for any missing data - there isn't

books %>% 
  summarise(across(.cols = everything(), .fns = ~sum(is.na(.x))))

# practising pull function to estimate what the rating is out of - data shows first 1,000 entries and appears to be a score out of 5

books %>% 
  pull(average_rating) 

### books %>% 
###  unique(average_rating) # I wanted to check that it is a score out of 5, this shows the unique values - Error: argument 'incomparables != FALSE' is not used (yet)

# find the mean average rating 

mean_average_rating <- books %>% 
  summarise(mean_average_rating = mean(average_rating)) %>% 
  pull(mean_average_rating)

mean_average_rating # 3.934075

# task - create a table showing only the books with a rating higher than the average with columns title, authors and language code

books %>% 
  filter(average_rating > mean_average_rating) 

books_tidy <- books %>% 
  select("title", "authors", "average_rating", "language_code") %>% 
  filter(average_rating > mean_average_rating) 
  
books_tidy # this is working, some columns are very wide though and looks ugly

head(books_tidy, 10) # show the first 10 rows of the tidy subset

View(head(books_tidy, 10)) # Much more readable like this


# task - sort the rows in order of rating with the best at the top

class(average_rating) # numeric as expected - note that data is a dbl which is part of the numeric set

books %>% 
  select(average_rating, title) %>%
  arrange(desc(average_rating))
  

# do head and tail to see at a glance the top and bottom values 



books %>% 
  head(arrange(desc(average_rating)))



# task - make a histogram and a boxplot of average_ratings

books %>% 
  hist(average_rating)



# task - make a barplot showing which languages are most frequent in the dataset

# first get that info in a table:

books %>% 
 select(language_code) %>% 
  count(language_code) %>% 
  arrange(desc(n)) 

# eng = 8908, en-US = 1408, spa = 218, en-GB = 214, fre = 144 etc

# task - add en-US and en-GB to the eng data

books2 <- books %>%
  mutate(language_code_group = if_else(
    language_code %in% c("eng", "en-US", "en-GB", "en-CA"),
    "eng",
    language_code)
  )


books %>% 
  barplot(c(language_code))


```




```{r}

books %>%
  arrange(desc(ratings_count)) %>% 
  select(title, ratings_count, average_rating) %>% 
  head(20) %>% 
  ggplot() + 
  aes(x = title, y = average_rating) +
  geom_col() + 
  coord_flip() +
  labs(title = "Top 20 Most Rated Books",
       x = "",
       y = "Ratings Count") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), 
        axis.text.y = element_text(angle = 0))


```


```{r}
install.packages(lubridate) # error - not found
library(lubridate)

books_data <- read_csv("data/books.csv")
d_adams <- filter(books_data, authors == "Douglas Adams")
d_adams

d_adams <- books %>%
  filter(authors == "Douglas Adams") %>%
  mutate(date = mdy(publication_date))

d_adams %>%
  arrange(date)
## date is a character vector not dates

d_adams %>%
  ggplot() +
  aes(x = date, y = average_rating) +
  geom_line(col = "red") +
  geom_point(col = "red") +
  labs(
    x = "Publication Date",
    y = "Average Rating",
    title = "Douglas Adams Books",
    subtitle = "Publication Dates and Average Ratings"
  )


```


```{r}
books_by_year<- books %>%
  mutate(year = format(as.Date(books$publication_date, format="%m/%d/%Y"),"%Y"), .after = publication_date) %>%
group_by(year) %>%   # here we can see that these books were published between 1900 and 2020
  group_by(authors)
  #summarise(Number_of_book_per_year = n())
  ggplot(books_by_year, aes(x = year, y = authors)) + geom_point()
labs( title = "books published between 1900 and 2020")
```

```{r}
books_by_year<- books %>%
  mutate(
    year = year(as.Date(publication_date, format="%m/%d/%Y")), .after = publication_date)

ggplot(books_by_year) +
  aes(x = year) +
  geom_histogram(colour = "white") +
  labs(
    x = "",
    y = "Number of Books",
    title = "Number of Books per year",
    subtitle = "in GoodReads Data"
  )

```





